In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [9]:
csv_file = "Resources/fundamentals.csv"
fundamentals_df = pd.read_csv(csv_file)
fundamentals_df.head()

,Unnamed: 0,Ticker Symbol,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,...,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding
0,0,AAL,2012-12-31,3.068000e+09,-222000000.0,-1.961000e+09,23.0,-1.888000e+09,4.695000e+09,53.0,...,7.072000e+09,9.011000e+09,-7.987000e+09,2.489100e+10,1.690400e+10,2.485500e+10,-367000000.0,2012.0,-5.60,3.350000e+08
1,1,AAL,2013-12-31,4.975000e+09,-93000000.0,-2.723000e+09,67.0,-3.114000e+09,1.059200e+10,75.0,...,1.432300e+10,1.380600e+10,-2.731000e+09,4.500900e+10,4.227800e+10,2.674300e+10,0.0,2013.0,-11.25,1.630222e+08
2,2,AAL,2014-12-31,4.668000e+09,-160000000.0,-1.500000e+08,143.0,-5.311000e+09,1.513500e+10,60.0,...,1.175000e+10,1.340400e+10,2.021000e+09,4.120400e+10,4.322500e+10,4.265000e+10,0.0,2014.0,4.02,7.169154e+08
3,3,AAL,2015-12-31,5.102000e+09,352000000.0,-7.080000e+08,135.0,-6.151000e+09,1.159100e+10,51.0,...,9.985000e+09,1.360500e+10,5.635000e+09,4.278000e+10,4.841500e+10,4.099000e+10,0.0,2015.0,11.39,6.681299e+08
4,4,AAP,2012-12-29,2.409453e+09,-89482000.0,6.000000e+05,32.0,-2.711820e+08,5.202150e+08,23.0,...,3.184200e+09,2.559638e+09,1.210694e+09,3.403120e+09,4.613814e+09,6.205003e+09,-27095000.0,2012.0,5.29,7.328355e+07

In [11]:
fundamentals_df.columns

Index(['Unnamed: 0', 'Ticker Symbol', 'Period Ending', 'Accounts Payable',
       'Accounts Receivable', 'Add'l income/expense items', 'After Tax ROE',
       'Capital Expenditures', 'Capital Surplus', 'Cash Ratio',
       'Cash and Cash Equivalents', 'Changes in Inventories', 'Common Stocks',
       'Cost of Revenue', 'Current Ratio', 'Deferred Asset Charges',
       'Deferred Liability Charges', 'Depreciation',
       'Earnings Before Interest and Tax', 'Earnings Before Tax',
       'Effect of Exchange Rate',
       'Equity Earnings/Loss Unconsolidated Subsidiary', 'Fixed Assets',
       'Goodwill', 'Gross Margin', 'Gross Profit', 'Income Tax',
       'Intangible Assets', 'Interest Expense', 'Inventory', 'Investments',
       'Liabilities', 'Long-Term Debt', 'Long-Term Investments',
       'Minority Interest', 'Misc. Stocks', 'Net Borrowings', 'Net Cash Flow',
       'Net Cash Flow-Operating', 'Net Cash Flows-Financing',
       'Net Cash Flows-Investing', 'Net Income', 'Net Income Adjustments',
       'Net Income Applicable to Common Shareholders',
       'Net Income-Cont. Operations', 'Net Receivables', 'Non-Recurring Items',
       'Operating Income', 'Operating Margin', 'Other Assets',
       'Other Current Assets', 'Other Current Liabilities', 'Other Equity',
       'Other Financing Activities', 'Other Investing Activities',
       'Other Liabilities', 'Other Operating Activities',
       'Other Operating Items', 'Pre-Tax Margin', 'Pre-Tax ROE',
       'Profit Margin', 'Quick Ratio', 'Research and Development',
       'Retained Earnings', 'Sale and Purchase of Stock',
       'Sales, General and Admin.',
       'Short-Term Debt / Current Portion of Long-Term Debt',
       'Short-Term Investments', 'Total Assets', 'Total Current Assets',
       'Total Current Liabilities', 'Total Equity', 'Total Liabilities',
       'Total Liabilities & Equity', 'Total Revenue', 'Treasury Stock',
       'For Year', 'Earnings Per Share', 'Estimated Shares Outstanding'],
      dtype='object')

In [19]:
#Income Statement
income_df = fundamentals_df[["Ticker Symbol", "Period Ending", "Total Revenue", "Cost of Revenue", "Depreciation", "Income Tax", "Operating Income", "Sales, General and Admin."]]
income_df = income_df.rename(columns = {"Ticker Symbol": "Ticker", "Total Revenue": "Revenue", "Cost of Revenue": "COGS", "Income Tax": "Tax", "Sales, General and Admin.": "SG&A"} )
income_df.head()

,Ticker,Period Ending,Revenue,COGS,Depreciation,Tax,Operating Income,SG&A
0,AAL,2012-12-31,2.485500e+10,1.049900e+10,1.001000e+09,-5.690000e+08,1.480000e+08,1.297700e+10
1,AAL,2013-12-31,2.674300e+10,1.101900e+10,1.020000e+09,-3.460000e+08,1.399000e+09,1.291300e+10
2,AAL,2014-12-31,4.265000e+10,1.562000e+10,1.342000e+09,3.300000e+08,4.249000e+09,2.068600e+10
3,AAL,2015-12-31,4.099000e+10,1.109600e+10,1.487000e+09,-2.994000e+09,6.204000e+09,2.127500e+10
4,AAP,2012-12-29,6.205003e+09,3.106967e+09,1.895440e+08,2.364040e+08,6.573150e+08,2.440721e+09

In [ ]:
#Balance Sheet
balance_df = fundamentals_df[["Ticker", "Period Ending", "Accounts Receivable", "Accounts Payable", "Cash and Cash Equivalents", "Fixed Assets", "Goodwill", "Inventory", "Other Assets"]]
income_df = income_df.rename(columns = {"Ticker Symbol": "X", "Total Revenue": "Revenue", "Cost of Revenue": "COGS", "Income Tax": "Tax", "Sales, General and Admin.": "SG&A"} )
income_df.head()

In [ ]:
#Financial Ratios